'use strict';
// The life of the Prophet ﷺ, stories of the Companions, and teachings from real moments. Written for IQRA from the Qur'an,
// Sahih al-Bukhari and Sahih Muslim, and the classical biographies (Ibn Ishaq / Ibn Hisham). Where a detail rests on the
// biographies rather than the two Sahihs, the text says "reported in the Sira". Dates are the commonly given ones; AH counts
// from the Hijrah, and sources differ by a little on some days.

DISCOVER.stories.push(
  { id: 'sira-birth', shelf: 'sira', n: 1, title: 'Birth and orphanhood', ar: 'المولد واليتم', era: 'c. 570 CE, Makkah',
    p: [
      'Muhammad ﷺ was born in Makkah in the Year of the Elephant, to ‘Abdullah ibn ‘Abd al-Muttalib and Aminah bint Wahb of the tribe of Quraysh. His father had died before his birth. As was the custom, he was sent to a wet-nurse in the desert, Halimah of Banu Sa’d, where the air was clean and he learned pure Arabic.',
      'His mother died when he was about six, and his grandfather ‘Abd al-Muttalib took him in. When his grandfather died two years later, his uncle Abu Talib became his guardian. The Qur’an reminds him: "Did He not find you an orphan and give you refuge?"',
    ],
    l: ['The final Messenger knew loss early and understood the orphan.', 'Allah took care of him at every stage before the message came.'],
    v: [[93, 6, 8]], src: 'Qur’an 93:6–8; Sira of Ibn Ishaq' },
  { id: 'sira-youth', shelf: 'sira', n: 2, title: 'Al-Amin, the trustworthy', ar: 'الصادق الأمين', era: 'before 610 CE, Makkah',
    p: [
      'As a young man he tended sheep, and at about twelve travelled with Abu Talib to Syria, where, the biographies report, the monk Bahira noticed signs of prophethood in him. In Makkah he became so known for honesty that people called him al-Amin, the trustworthy, and left their valuables with him.',
      'Khadijah bint Khuwaylid, a respected widow and merchant, hired him to trade for her. Impressed by his honesty and character, she proposed marriage. He was twenty-five. It was a loving marriage that lasted until her death.',
      'When Quraysh rebuilt the Kaaba and quarrelled over who would set the Black Stone, it is reported that they agreed to accept the first man to enter. It was Muhammad. He laid the stone on a cloak and let each clan hold its edge, and so avoided a war.',
    ],
    l: ['His character was famous long before he preached.', 'Trust and honesty are the foundation of influence.'],
    src: 'Sira of Ibn Ishaq and Ibn Hisham' },
  { id: 'sira-hira', shelf: 'sira', n: 3, title: 'The first revelation', ar: 'الوحي الأول', era: 'Ramadan, c. 610 CE, Cave of Hira',
    p: [
      'Troubled by the idolatry around him, he went to the cave of Hira above Makkah to reflect. In his fortieth year, the angel Jibril came and said, "Read!" He answered, "I cannot read." Jibril pressed him three times and said: "Read in the name of your Lord who created."',
      'Shaken, he ran home to Khadijah: "Cover me!" She comforted him with words that history preserves: "Never! By Allah, Allah will never disgrace you. You keep family ties, you bear the burdens of the weak, you give to the poor, you honour the guest, and you help against hardships." She took him to her cousin Waraqah ibn Nawfal, who said: this is the same angel who came to Musa.',
      'This is reported in Sahih al-Bukhari and Sahih Muslim, narrated by ‘A’ishah.',
    ],
    l: ['Revelation began with "Read", with knowledge.', 'Khadijah recognised his goodness before she understood his mission.'],
    v: [[96, 1, 5]], src: 'Sahih al-Bukhari and Sahih Muslim (‘A’ishah); Qur’an 96:1–5' },
  { id: 'sira-early-call', shelf: 'sira', n: 4, title: 'The quiet call and the public call', ar: 'الدعوة', era: '610–613 CE, Makkah',
    p: [
      'For about three years he invited people privately. The first to believe were Khadijah, his young cousin ‘Ali, his freed servant Zayd ibn Harithah, and his close friend Abu Bakr, who brought others. They met at the house of al-Arqam.',
      'When he was commanded to warn his closest relatives, he climbed Mount Safa and called out to Quraysh. When they gathered he asked: "If I told you an army was behind this mountain, would you believe me?" They said: "We have never known you to lie." He then warned them of a severe punishment. His uncle Abu Lahab cursed him, and Surah al-Masad was revealed about him.',
    ],
    l: ['He began with those who knew him best, and they believed.', 'Even those who rejected him admitted he never lied.'],
    v: [[26, 214, 216], [111, 1, 5]], src: 'Sahih al-Bukhari and Sahih Muslim (Safa); Sira' },
  { id: 'sira-persecution', shelf: 'sira', n: 5, title: 'Persecution in Makkah', ar: 'الإيذاء', era: 'c. 613–615 CE, Makkah',
    p: [
      'As the call spread, Quraysh turned to mockery and then to torture, mainly against the weak. Bilal was dragged over the hot sand with a rock on his chest, repeating "Ahad, Ahad" (One, One). Sumayyah and her husband Yasir were killed, becoming the first martyrs of Islam. Khabbab was burned on hot coals.',
      'When Khabbab complained, the Prophet ﷺ reminded him of earlier believers who were sawn in two and combed with iron combs, and said Allah would complete this matter until a traveller could ride from Sana’a to Hadramawt fearing only Allah (Sahih al-Bukhari).',
    ],
    l: ['Faith was never promised to be free of hardship.', 'Steadfastness under torture became the foundation of the community.'],
    v: [[29, 2, 3]], src: 'Sahih al-Bukhari (Khabbab); Sira' },
  { id: 'sira-abyssinia', shelf: 'sira', n: 6, title: 'Refuge in Abyssinia', ar: 'الهجرة إلى الحبشة', era: '615 CE',
    p: [
      'With the persecution worsening, the Prophet ﷺ told some Muslims to go to Abyssinia, where, he said, there was a king under whom no one is wronged. A small group left first, then a larger one, about eighty, led by Ja’far ibn Abi Talib.',
      'Quraysh sent envoys with gifts to bring them back. The Negus, the Christian king, asked the Muslims about their faith. Ja’far explained how Islam had changed them and recited the opening of Surah Maryam. The Negus wept. He said that what they recited and what ‘Isa brought came from the same lamp, and refused to hand them over. (As reported in the Sira.)',
    ],
    l: ['Protect your faith and your people, even by leaving.', 'Truth can win a fair-minded listener in a different land.'],
    v: [[19, 1, 15]], src: 'Sira of Ibn Ishaq and Musnad Ahmad' },
  { id: 'sira-sorrow', shelf: 'sira', n: 7, title: 'The boycott and the Year of Sorrow', ar: 'عام الحزن', era: 'c. 616–619 CE',
    p: [
      'Quraysh agreed to boycott the Prophet’s ﷺ clan, Banu Hashim, refusing trade or marriage with them. For about three years his family endured hunger in a valley, the Shi’b of Abu Talib. It ended when some of Quraysh themselves cancelled the pact.',
      'Soon afterwards, in the same year, both his uncle Abu Talib, who had protected him, and his wife Khadijah died. It became known as the Year of Sorrow. Without his protector, the persecution grew harder.',
    ],
    l: ['Even the Prophet ﷺ lost those closest to him.', 'Grief and patience belong together.'],
    src: 'Sira of Ibn Ishaq' },
  { id: 'sira-taif', shelf: 'sira', n: 8, title: 'Ta’if: the hardest day', ar: 'الطائف', era: 'c. 619 CE',
    p: [
      'Seeking support, he went to the town of Ta’if. Its leaders rejected him, mocked him and sent their children and servants to pelt him with stones until his feet bled. He sheltered in an orchard, deeply hurt.',
      '‘A’ishah once asked him if any day was harder than Uhud. He said that the worst he had suffered was at ‘Aqabah on that day. On his way back, he looked up and saw a cloud with Jibril in it, and the angel of the mountains who said: "If you wish, I will close the two mountains on them." He answered: "No. I hope that Allah will bring from their descendants people who worship Allah alone." (Sahih al-Bukhari and Sahih Muslim)',
    ],
    l: ['At his lowest moment he chose mercy.', 'He looked to the future generation, not the present anger.'],
    src: 'Sahih al-Bukhari and Sahih Muslim (‘A’ishah)' },
  { id: 'sira-isra', shelf: 'sira', n: 9, title: 'Al-Isra’ wal-Mi’raj', ar: 'الإسراء والمعراج', era: 'c. 620 CE',
    p: [
      'In one night Allah took His servant from the Sacred Mosque in Makkah to al-Aqsa in Jerusalem, and then raised him through the heavens, meeting earlier prophets. He saw Jibril in his true form at the Lote-Tree of the Boundary.',
      'On that night, the prayers were prescribed: first fifty a day. On the way back, Musa advised him to ask for a reduction, again and again, until it was five. Allah said they are five in number but fifty in reward. (Sahih al-Bukhari and Sahih Muslim)',
    ],
    l: ['The prayer was given directly, on a night of comfort after hardship.', 'Five prayers carry the reward of fifty.'],
    v: [[17, 1], [53, 13, 18]], src: 'Qur’an 17:1, 53:1–18; Sahih al-Bukhari and Sahih Muslim' },
  { id: 'sira-aqaba', shelf: 'sira', n: 10, title: 'The pledges at ‘Aqabah', ar: 'بيعة العقبة', era: '621–622 CE',
    p: [
      'Each pilgrimage season the Prophet ﷺ met tribes. Six men from Yathrib (later Madinah) believed, then a dozen came the next year and pledged not to associate anything with Allah, steal or commit adultery. He sent Mus’ab ibn ‘Umayr with them to teach the Qur’an, and Islam spread in nearly every house in Yathrib.',
      'The next year, over seventy people came and pledged to protect him as they would their own families. The path to Hijrah was open.',
    ],
    l: ['Quiet teaching by one dedicated person can change a city.', 'The Ansar pledged protection when others had closed their doors.'],
    src: 'Sira of Ibn Ishaq; Musnad Ahmad' },
  { id: 'sira-hijrah', shelf: 'sira', n: 11, title: 'The Hijrah', ar: 'الهجرة', era: '622 CE',
    p: [
      'Quraysh agreed to have one man from each clan strike him together. The night they came, ‘Ali slept in his bed. The Prophet ﷺ left home with Abu Bakr, reciting the opening of Ya-Sin, and hid in the cave of Thawr. Abu Bakr’s daughter Asma’ carried them food, and tore her waist-belt in two for the bags, earning the name "She of the two belts."',
      'When the pursuers reached the mouth of the cave, Abu Bakr whispered, "If one of them looks down at his feet, he will see us." The Prophet ﷺ answered: "What do you think of two when Allah is their third?" (Sahih al-Bukhari). The Qur’an records it: "Do not grieve; indeed Allah is with us."',
      'After days of travel they reached Quba, then Madinah, where the people came out to welcome him. This journey marks the start of the Islamic calendar.',
    ],
    l: ['Plan carefully, then trust Allah completely.', 'Real companionship is being willing to be in danger with someone.'],
    v: [[9, 40]], src: 'Qur’an 9:40; Sahih al-Bukhari (Abu Bakr); Sira' },
  { id: 'sira-madinah', shelf: 'sira', n: 12, title: 'Building Madinah', ar: 'بناء المجتمع', era: '622–623 CE',
    p: [
      'His first act in Madinah was to build a mosque, working with the Companions carrying bricks. It was a place of prayer, learning and community. Then he paired Muhajirun (emigrants) with Ansar (helpers) as brothers. Sa’d ibn al-Rabi’ offered his brother ‘Abd al-Rahman ibn ‘Awf half his wealth and even to choose a wife. ‘Abd al-Rahman replied, "May Allah bless you in your family and wealth. Show me the market," and began trading. (Sahih al-Bukhari)',
      'The Prophet ﷺ also agreed a charter with the Jewish tribes and others in Madinah, known as the Constitution of Madinah, establishing mutual defence and rights. The adhan was introduced, and Bilal became the first caller to prayer.',
    ],
    l: ['A community starts with a place to gather and a bond of brotherhood.', 'Generosity on one side and dignity on the other: he asked for the market, not a handout.'],
    src: 'Sahih al-Bukhari (‘Abd al-Rahman ibn ‘Awf); Sira' },
  { id: 'sira-badr', shelf: 'sira', n: 13, title: 'Badr', ar: 'غزوة بدر', era: '17 Ramadan, 2 AH',
    p: [
      'About 313 Muslims with few horses and a handful of camels met a Quraysh army of nearly a thousand at the wells of Badr. The night before, the Prophet ﷺ spent the night in prayer and rain fell. In the battle, the Muslims won decisively. Allah says He helped them although they were few.',
      'It is known as the Day of Criterion (Furqan), the day truth and falsehood were separated. After the battle, the prisoners were treated kindly, and some of those who could write were reportedly freed in exchange for teaching Muslim children to write.',
    ],
    l: ['Victory is from Allah, though effort is required.', 'Treat prisoners with mercy.'],
    v: [[3, 123, 126], [8, 9, 12]], src: 'Qur’an 3:123–126, 8:5–19; Sira' },
  { id: 'sira-uhud', shelf: 'sira', n: 14, title: 'Uhud', ar: 'غزوة أحد', era: 'Shawwal, 3 AH',
    p: [
      'The Muslims, around seven hundred, faced about three thousand. The Prophet ﷺ placed fifty archers on a hill and told them not to leave their position whatever happened. When the Muslims began to win, most of the archers left for the spoils. Quraysh cavalry circled behind, and the tide turned.',
      'The Prophet ﷺ was wounded. Seventy Muslims were killed, including his uncle Hamza. Allah consoled them in Surah Al ‘Imran: "Do not weaken and do not grieve, and you will be superior if you are believers," and reminded them that the loss came from a failure to obey a command (Sahih al-Bukhari).',
    ],
    l: ['Obedience to the leader’s clear instruction matters more than personal calculation.', 'Even a defeat is a lesson and a mercy.'],
    v: [[3, 139, 143], [3, 152]], src: 'Qur’an 3:121–175; Sahih al-Bukhari (the archers)' },
  { id: 'sira-trench', shelf: 'sira', n: 15, title: 'The Trench', ar: 'غزوة الخندق', era: 'Shawwal, 5 AH',
    p: [
      'A coalition of Arab tribes, about ten thousand, marched on Madinah. Salman al-Farisi, a Persian, is reported to have suggested digging a trench, a defence unknown to the Arabs. The Companions dug it in freezing weather, hungry, with the Prophet ﷺ digging beside them and tying a stone to his stomach against hunger (Sahih al-Bukhari).',
      'For weeks the armies sat on either side of it, until a cold wind and storm broke their camp, and they left. The Qur’an remembers how the believers were shaken, then said: "This is what Allah and His Messenger promised us."',
    ],
    l: ['Good ideas can come from anyone.', 'Leaders share the hardship.'],
    v: [[33, 9, 11]], src: 'Qur’an 33:9–27; Sahih al-Bukhari' },
  { id: 'sira-hudaybiyyah', shelf: 'sira', n: 16, title: 'Al-Hudaybiyyah: a clear victory', ar: 'صلح الحديبية', era: 'Dhul-Qa’dah, 6 AH',
    p: [
      'The Prophet ﷺ set out with about fourteen hundred Companions in a state of ihram to perform ‘umrah. Quraysh stopped them at Hudaybiyyah. After tense talks, a treaty was agreed with terms that seemed unfair, such as sending back anyone fleeing Makkah to join the Muslims. Many Companions, including ‘Umar, were upset.',
      'He told them to sacrifice and shave their heads, and no one moved. His wife Umm Salamah advised: go out and do it yourself without speaking to anyone. When he did, they followed. Allah then revealed Surah al-Fath: "Indeed We have given you a clear conquest." The truce let Islam spread in peace, and the early historians note that more people entered Islam in the following two years than in all the years before. (The sacrifice and Umm Salamah’s advice are in Sahih al-Bukhari.)',
    ],
    l: ['What looks like a setback may open the way.', 'Lead by doing, and listen to good counsel.'],
    v: [[48, 1, 4]], src: 'Qur’an 48; Sahih al-Bukhari' },
  { id: 'sira-letters', shelf: 'sira', n: 17, title: 'Letters to the rulers', ar: 'الرسائل إلى الملوك', era: '6–7 AH',
    p: [
      'After Hudaybiyyah, the Prophet ﷺ sent letters to the rulers of the time: Heraclius of Byzantium, Khosrow of Persia, the Negus of Abyssinia, the Muqawqis of Egypt and others, inviting them to Islam. The letter to Heraclius is quoted in Sahih al-Bukhari: "Peace be upon whoever follows guidance. Accept Islam and you will be safe..."',
      'Heraclius asked questions of Abu Sufyan, then still an opponent, about the Prophet’s lineage, truthfulness and followers, and judged these to be signs of a prophet. The Negus accepted Islam. Khosrow tore up the letter.',
    ],
    l: ['The message was meant for all humanity.', 'Even his enemy Abu Sufyan could not deny his truthfulness.'],
    src: 'Sahih al-Bukhari (letter to Heraclius); Sira' },
  { id: 'sira-mutah', shelf: 'sira', n: 18, title: 'Mu’tah', ar: 'غزوة مؤتة', era: '8 AH',
    p: [
      'A Muslim envoy was killed by a Byzantine ally, so the Prophet ﷺ sent an army of three thousand under Zayd ibn Harithah, saying: if Zayd is killed, Ja’far takes command, and if Ja’far is killed, ‘Abdullah ibn Rawahah. They faced a force many times larger. All three commanders fell in turn.',
      'In Madinah, the Prophet ﷺ told the people of their deaths with tears in his eyes, before the news reached them. Khalid ibn al-Walid then took the banner, and was called "a sword among the swords of Allah." (Sahih al-Bukhari)',
    ],
    l: ['Leaders led from the front and died for what they believed.', 'The community kept going when its leaders fell.'],
    src: 'Sahih al-Bukhari' },
  { id: 'sira-conquest', shelf: 'sira', n: 19, title: 'The Conquest of Makkah', ar: 'فتح مكة', era: 'Ramadan, 8 AH (630 CE)',
    p: [
      'After Quraysh broke the treaty, the Prophet ﷺ marched on Makkah with ten thousand. He entered with his head bowed so low it nearly touched his camel, in thankfulness. He cleaned the Kaaba of its idols, saying: "The truth has come, and falsehood has vanished."',
      'The people who had persecuted, boycotted and driven him out awaited his verdict. As reported in the Sira, he asked: "What do you think I will do with you?" They said: "Good. You are a noble brother, son of a noble brother." He said: "Go, for you are free." Bilal climbed the Kaaba and called the adhan. Surah an-Nasr was soon revealed.',
    ],
    l: ['Victory was met with humility and pardon, not revenge.', 'Mercy won more hearts than force.'],
    v: [[17, 81], [110, 1, 3]], src: 'Qur’an 17:81, 110; Sahih al-Bukhari and Sahih Muslim (the Kaaba); Sira' },
  { id: 'sira-hunayn', shelf: 'sira', n: 20, title: 'Hunayn and the Ansar', ar: 'غزوة حنين', era: 'Shawwal, 8 AH',
    p: [
      'At Hunayn, the Muslims, now twelve thousand, felt confident in their numbers and were caught in an ambush. For a moment many fled, until the Prophet ﷺ called them back and they recovered. The Qur’an says: "Your great number did not avail you."',
      'In the distribution of the spoils, he gave generously to new Muslims, to win their hearts. Some Ansar felt hurt. He gathered them and said: "Are you not content that the people go with sheep and camels while you return with the Messenger of Allah to your homes?" They wept until their beards were wet and said: "We are content." (Sahih al-Bukhari and Sahih Muslim)',
    ],
    l: ['Numbers do not decide victory.', 'He made loyal people feel valued, and they were moved to tears.'],
    v: [[9, 25, 26]], src: 'Qur’an 9:25–26; Sahih al-Bukhari and Sahih Muslim' },
  { id: 'sira-tabuk', shelf: 'sira', n: 21, title: 'Tabuk and the three who stayed behind', ar: 'غزوة تبوك', era: 'Rajab, 9 AH',
    p: [
      'The Prophet ﷺ called the Muslims to march in the heat of summer against the Byzantines at Tabuk. Wealthy Companions gave large amounts, including ‘Uthman, who equipped much of the army, and Abu Bakr, who gave everything he owned.',
      'Three Companions, Ka’b ibn Malik, Murarah ibn al-Rabi’ and Hilal ibn Umayyah, stayed behind without a valid excuse. When the Prophet ﷺ returned, the hypocrites made excuses; Ka’b chose to tell the truth. The three were shunned by the community for fifty days, until Allah accepted their repentance. Ka’b said that truthfulness was the reason he was saved, and he promised never to lie again. (Sahih al-Bukhari and Sahih Muslim)',
    ],
    l: ['Honest repentance, even when hard, is the way out.', 'The community can hold its members accountable and still welcome them back.'],
    v: [[9, 117, 119]], src: 'Qur’an 9:117–119; Sahih al-Bukhari and Sahih Muslim (Ka’b ibn Malik)' },
  { id: 'sira-farewell', shelf: 'sira', n: 22, title: 'The Farewell Pilgrimage', ar: 'حجة الوداع', era: '10 AH (632 CE)',
    p: [
      'In his only Hajj, with over a hundred thousand Muslims, he stood at Arafah and gave a sermon. As recorded in Sahih Muslim (Jabir): your blood and your wealth are sacred, like the sanctity of this day, this month and this city; all interest from the Days of Ignorance is cancelled; fear Allah regarding women, for you have rights over them and they have rights over you; and "I have left among you something that, if you hold to it, you will never go astray: the Book of Allah."',
      'He asked the people: "Have I conveyed the message?" They answered: "Yes." He raised his finger to the sky and said: "O Allah, be witness." On that Arafah, the verse was revealed: "This day I have perfected for you your religion and completed My favour upon you."',
    ],
    l: ['Human life, property and dignity are sacred.', 'Hold on to the Qur’an.'],
    v: [[5, 3]], src: 'Sahih Muslim (Jabir); Sahih al-Bukhari; Qur’an 5:3' },
  { id: 'sira-passing', shelf: 'sira', n: 23, title: 'His passing', ar: 'الوفاة', era: '12 Rabi’ al-Awwal, 11 AH (632 CE)',
    p: [
      'He fell ill and, with the permission of his wives, stayed in ‘A’ishah’s house. As he grew weaker, he asked Abu Bakr to lead the prayer. He is reported to have urged, near the end, "the prayer, and those under your care." He passed away on a Monday with his head on ‘A’ishah’s chest (Sahih al-Bukhari).',
      'The Companions were stunned; ‘Umar could not believe it. Abu Bakr entered, kissed him, then went out and said: "Whoever worshipped Muhammad, Muhammad has died. Whoever worships Allah, Allah is Ever-Living and does not die." He recited: "Muhammad is no more than a messenger; messengers have passed before him." The people felt as if they had never heard it before. (Sahih al-Bukhari)',
    ],
    l: ['The Prophet was human, and the message is for Allah alone.', 'Abu Bakr’s steadiness held the community together.'],
    v: [[3, 144]], src: 'Sahih al-Bukhari (‘A’ishah, Abu Bakr); Qur’an 3:144' },
);

DISCOVER.stories.push(
  { id: 'c-khadijah', shelf: 'companions', title: 'Khadijah, the first believer', ar: 'خديجة',
    p: [
      'Khadijah bint Khuwaylid was a successful businesswoman, known in Makkah as "the pure one". She hired Muhammad ﷺ to trade for her, proposed to him, and was his wife for about twenty-five years. When revelation came and he was frightened, she was the first person to believe in him.',
      'She spent her wealth in support of Islam, stood by him in the boycott, and the Prophet ﷺ remembered her with love all his life. Jibril conveyed Allah’s greetings to her, with news of a house in Paradise (Sahih al-Bukhari and Sahih Muslim).',
    ],
    l: ['Support at the right moment can change history.', 'Faith and generosity go together.'], src: 'Sahih al-Bukhari and Sahih Muslim; Sira' },
  { id: 'c-abu-bakr', shelf: 'companions', title: 'Abu Bakr as-Siddiq', ar: 'أبو بكر الصديق',
    p: [
      'Abu Bakr was the first man outside the family to believe, and he never hesitated: when told about the Isra’ and Mi’raj he is reported to have said, "If he said it, it is true." That is the origin of his title as-Siddiq, "the one who affirms the truth."',
      'He bought and freed enslaved Muslims such as Bilal. He was the Prophet’s ﷺ companion in the cave. When the army was equipped for Tabuk, he brought everything he owned, and when asked what he had left for his family, said: "Allah and His Messenger." After the Prophet’s ﷺ death he steadied the community and became the first caliph.',
    ],
    l: ['Belief without delay and sacrifice without counting.', 'Calm in crisis: his words at the Prophet’s death held people together.'], src: 'Sahih al-Bukhari; Sunan Abi Dawud and at-Tirmidhi (Tabuk gift); Sira' },
  { id: 'c-umar', shelf: 'companions', title: '‘Umar ibn al-Khattab', ar: 'عمر بن الخطاب',
    p: [
      '‘Umar was known for his strength and was at first a harsh opponent. As reported in the Sira, he set out to find the Prophet ﷺ and heard that his own sister had accepted Islam. Finding her reading from Surah Ta-Ha, he asked to read it, and his heart softened. He went to the Prophet ﷺ and accepted Islam.',
      '‘Abdullah ibn Mas’ud said: "We have been strong since ‘Umar became Muslim" (Sahih al-Bukhari), as Muslims could now pray openly at the Kaaba. As the second caliph he was known for justice, for patrolling at night to check on the poor, and for expanding the Muslim state.',
    ],
    l: ['A heart can change when it meets the Qur’an.', 'Strength is best used for justice.'], src: 'Sahih al-Bukhari; Sira' },
  { id: 'c-bilal', shelf: 'companions', title: 'Bilal ibn Rabah', ar: 'بلال بن رباح',
    p: [
      'Bilal was an Abyssinian slave in Makkah whose master tortured him for believing, laying a rock on his chest in the midday heat. He kept saying "Ahad, Ahad." Abu Bakr bought and freed him.',
      'In Madinah he became the first mu’adhdhin. The Prophet ﷺ once told him: "Bilal, tell me about the deed you did in Islam that you hope most for, for I heard the sound of your footsteps ahead of me in Paradise." Bilal said: "I do not do anything greater than this, that whenever I make wudu, day or night, I pray with that wudu what Allah has written for me." (Sahih al-Bukhari and Sahih Muslim). At the conquest of Makkah, he called the adhan from the Kaaba.',
    ],
    l: ['Worth in Islam is faith and deeds, not origin or status.', 'A small consistent habit raised him high.'], src: 'Sahih al-Bukhari and Sahih Muslim; Sira' },
  { id: 'c-ali', shelf: 'companions', title: '‘Ali ibn Abi Talib', ar: 'علي بن أبي طالب',
    p: [
      '‘Ali was raised in the Prophet’s ﷺ household and was among the first to accept Islam as a boy. On the night of the Hijrah he slept in the Prophet’s ﷺ bed, to deceive those waiting outside to kill him.',
      'At Khaybar the Prophet ﷺ said: "Tomorrow I will give the banner to a man who loves Allah and His Messenger, and whom Allah and His Messenger love." The next morning it was given to ‘Ali, and by Allah’s help the fortress fell (Sahih al-Bukhari and Sahih Muslim). Known for his knowledge, courage and eloquence, he became the fourth caliph.',
    ],
    l: ['Faith from childhood, courage when it counts.', 'Trust of the Prophet was earned by deeds.'], src: 'Sahih al-Bukhari and Sahih Muslim; Sira' },
  { id: 'c-uthman', shelf: 'companions', title: '‘Uthman ibn ‘Affan', ar: 'عثمان بن عفان',
    p: [
      '‘Uthman was a wealthy, modest and shy man, so much so that the Prophet ﷺ said even the angels are shy of him (Sahih Muslim). He was twice the Prophet’s ﷺ son-in-law. When Madinah lacked a good water source, he bought the well of Rumah and made it free for all; at Tabuk he equipped a large part of the army.',
      'As the third caliph, he had the Qur’an copied into standard volumes and sent to the main cities, preserving its unity for all later generations (Sahih al-Bukhari).',
    ],
    l: ['Wealth used for the community is a lasting charity.', 'He protected the Book for everyone who came after.'], src: 'Sahih Muslim; Sahih al-Bukhari (copying the Qur’an); Sunan at-Tirmidhi (Tabuk)' },
  { id: 'c-aisha', shelf: 'companions', title: '‘A’ishah bint Abi Bakr', ar: 'عائشة',
    p: [
      '‘A’ishah, the Prophet’s ﷺ wife, became one of the greatest scholars of her time. She narrated over two thousand hadith, and senior Companions came to her with questions of law and the Prophet’s ﷺ private conduct. She is remembered for correcting others when their memory slipped.',
      'Asked about the Prophet’s ﷺ behaviour at home, she said he used to help his family with chores, and when it was time for prayer he would get up and go. (Sahih al-Bukhari)',
    ],
    l: ['Women have been teachers of religion from the very beginning.', 'Knowledge is preserved by those who live close to the source.'], src: 'Sahih al-Bukhari; Sira' },
  { id: 'c-musab', shelf: 'companions', title: 'Mus’ab ibn ‘Umayr', ar: 'مصعب بن عمير',
    p: [
      'Mus’ab was the best-dressed young man of Makkah, from a wealthy family who doted on him. When he accepted Islam, his family tried to force him back and took away his comforts, and he gave it all up.',
      'The Prophet ﷺ chose him to teach the first Muslims of Madinah. Within a year, nearly every house had been touched by Islam. He was killed at Uhud, holding the banner. Khabbab said that when he died, he left only a striped cloak: if they covered his head, his feet showed, and if they covered his feet, his head showed. (Sahih al-Bukhari)',
    ],
    l: ['Comfort was exchanged for the cause.', 'One well-prepared teacher can open a whole city.'], src: 'Sahih al-Bukhari; Sira' },
  { id: 'c-sumayyah', shelf: 'companions', title: 'Sumayyah bint Khayyat', ar: 'سمية',
    p: [
      'Sumayyah and her husband Yasir and their son ‘Ammar were among the early believers without tribal protection. The Prophet ﷺ passed them while they were being tortured and said: "Be patient, family of Yasir, for your meeting place is Paradise."',
      'As reported in the Sira, Abu Jahl killed Sumayyah when she would not renounce her faith, so she became the first martyr in Islam.',
    ],
    l: ['Faith is not dependent on tribe or power.', 'Her steadfastness is remembered more than any of her persecutors.'], src: 'Sira of Ibn Ishaq and Ibn Sa’d' },
  { id: 'c-salman', shelf: 'companions', title: 'Salman the Persian', ar: 'سلمان الفارسي',
    p: [
      'Salman grew up in a Zoroastrian family in Persia and left to seek the truth. He lived with Christian monks in Syria and Iraq, each pointing him to the next, until one told him the awaited prophet would appear in Arabia. On the way he was sold into slavery, and ended in Madinah.',
      'There, he recognised the signs he had been told about and accepted Islam. After being freed, he gave the idea of digging the trench at the Battle of the Trench. (As reported in the Sira and Musnad Ahmad.)',
    ],
    l: ['A lifelong search ended in the truth.', 'A newcomer’s idea can save the whole community.'], src: 'Sira; Musnad Ahmad' },
  { id: 'c-ibn-masud', shelf: 'companions', title: '‘Abdullah ibn Mas’ud and the Qur’an', ar: 'عبد الله بن مسعود',
    p: [
      'Ibn Mas’ud was a young shepherd who became one of the great reciters. Early in Makkah, he asked to recite the Qur’an aloud in front of Quraysh at the Kaaba; they beat him, but he went again the next day. (As reported in the Sira.)',
      'The Prophet ﷺ once asked him to recite to him. He said, "Shall I recite to you when it was revealed to you?" He replied, "I love to hear it from someone else." When Ibn Mas’ud reached the verse "How will it be when We bring from every nation a witness...", the Prophet ﷺ said "Enough," and his eyes were flowing with tears. (Sahih al-Bukhari and Sahih Muslim)',
    ],
    l: ['Courage to recite openly, and the humility to listen.', 'The Qur’an moved even the one who received it.'], v: [[4, 41]], src: 'Sahih al-Bukhari and Sahih Muslim; Sira' },
  { id: 'c-umm-sulaym', shelf: 'companions', title: 'Umm Sulaym and her dowry', ar: 'أم سليم',
    p: [
      'Abu Talhah proposed to Umm Sulaym, a widow with a son (Anas), before he became Muslim. She said: "A man like you is not turned down, but you are a disbeliever and I am a Muslim, and it is not lawful for me to marry you. If you become Muslim, that will be my dowry, and I ask nothing else."',
      'He accepted Islam and they married. Thabit, one of the narrators, said he had never heard of a dowry better than hers. (an-Nasa’i, graded sound)',
    ],
    l: ['Faith valued above wealth or status.', 'A dignified and clear-minded woman changed a man’s life.'], src: 'Sunan an-Nasa’i' },
);

DISCOVER.stories.push(
  { id: 's-bedouin', shelf: 'situations', title: 'The man who urinated in the mosque', ar: 'الأعرابي في المسجد',
    p: [
      'A Bedouin stood and began to urinate in the mosque. The Companions rushed at him, but the Prophet ﷺ said: "Leave him, and pour a bucket of water over where he urinated. You were sent to make things easy, not to make them hard."',
      'He then called the man and explained gently that mosques are not for urine or filth, but for the remembrance of Allah, prayer and the recitation of the Qur’an. (Sahih al-Bukhari and Sahih Muslim, narrated by Anas)',
    ],
    l: ['Teach with gentleness: hearts open to kindness.', 'Prevent harm, but do not humiliate.'], src: 'Sahih al-Bukhari and Sahih Muslim' },
  { id: 's-hasan', shelf: 'situations', title: 'Kissing his grandson', ar: 'تقبيل الحسن',
    p: [
      'The Prophet ﷺ kissed his grandson al-Hasan. Al-Aqra’ ibn Habis, a chieftain, who was sitting there said: "I have ten children and have never kissed any of them." The Prophet ﷺ looked at him and said: "Whoever does not show mercy will not be shown mercy." (Sahih al-Bukhari and Sahih Muslim)',
    ],
    l: ['Affection is part of the faith, not weakness.', 'Mercy toward children is a duty.'], src: 'Sahih al-Bukhari and Sahih Muslim' },
  { id: 's-grave', shelf: 'situations', title: 'The woman at the grave', ar: 'المرأة عند القبر',
    p: [
      'The Prophet ﷺ passed a woman weeping at a grave and told her: "Fear Allah and be patient." Not recognising him, she snapped: "Go away, you are not stricken with my calamity." When she was told it was the Prophet ﷺ, she went to his door and found no doorkeeper. She said: "I did not recognise you." He said: "Patience is at the first stroke of the calamity." (Sahih al-Bukhari and Sahih Muslim)',
    ],
    l: ['He accepted harsh words from someone in pain, without anger.', 'The reward is for the patience shown at the first moment.'], src: 'Sahih al-Bukhari and Sahih Muslim (Anas)' },
  { id: 's-funeral', shelf: 'situations', title: 'Standing for a funeral', ar: 'القيام للجنازة',
    p: [
      'A funeral procession passed by, and the Prophet ﷺ stood up. Told that it was the funeral of a Jewish man, he said: "Is it not a soul?" (Sahih al-Bukhari and Sahih Muslim)',
    ],
    l: ['Every human life deserves respect.', 'Death is a reminder, whoever it is.'], src: 'Sahih al-Bukhari and Sahih Muslim' },
  { id: 's-usama', shelf: 'situations', title: 'Usamah and the man who said the shahadah', ar: 'أسامة',
    p: [
      'In a raid, Usamah ibn Zayd and an Ansari man caught a fleeing enemy. As Usamah raised his sword, the man said: "La ilaha illallah." Usamah struck and killed him anyway. When the Prophet ﷺ heard, he said: "Did you kill him after he said La ilaha illallah?" Usamah explained that the man said it only to save himself. The Prophet ﷺ kept repeating: "Did you split his heart open to know that?" Usamah said he wished he had not been Muslim before that day. (Sahih al-Bukhari and Sahih Muslim)',
    ],
    l: ['We judge what we see, and leave hearts to Allah.', 'Shedding blood is a very grave matter.'], src: 'Sahih al-Bukhari and Sahih Muslim' },
  { id: 's-anas', shelf: 'situations', title: 'Ten years of service', ar: 'خدمة أنس',
    p: [
      'Anas ibn Malik served the Prophet ﷺ from the age of about ten for ten years. He said: "I served him for ten years. He never said ‘uff’ to me, never asked why I did something, and never asked why I did not do something." (Sahih al-Bukhari and Sahih Muslim)',
      '‘A’ishah said he never struck anything with his hand, neither a servant nor a woman, except in the cause of Allah (Sahih Muslim).',
    ],
    l: ['Patience with those under your care.', 'Good character is the best argument for the faith.'], src: 'Sahih al-Bukhari and Sahih Muslim' },
  { id: 's-najran', shelf: 'situations', title: 'The Christians of Najran in his mosque', ar: 'وفد نجران',
    p: [
      'A delegation of Christians from Najran came to Madinah to meet the Prophet ﷺ. They discussed faith with him, and when their time of prayer came, he let them pray in his mosque. (As reported in the Sira, by Ibn Ishaq.)',
      'The Qur’an records the discussion about ‘Isa and invites them to a common word: that we worship none but Allah and associate nothing with Him.',
    ],
    l: ['Dignity and hospitality towards guests of other faiths.', 'The invitation was to common ground.'], v: [[3, 59, 64]], src: 'Sira of Ibn Ishaq; Qur’an 3:59–64' },
);
